### ISSUE TITLE
Feature Request: Reinstate nightly

### ISSUE THREAD

**Issue by johnbillion** [roots/wordpress-full#3]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

It looks like [support for nightly](https://github.com/roots/wordpress/issues/6) went missing with the move from `roots/wordpress` to `roots/wordpress-full`. It would be great to get that back.

Cheers!

#### Why are we doing this?

I use `dev-nightly` to automatically test my plugins against nightlies using CI.

**Comment by johnbillion** [comment]
Ah the `main` branch points to the nightly build, so `dev-main` can be used. Cheers.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @johnbillion.
You can use the `dev-main` (or `@dev`) version to use the latest nightly.
In the meantime, `roots/wordpress` still have the git/svn-powered nightlies.

**Comment by LeoColomb** [comment]
In a nice timing 😊
